f=open("python.txt","w")
f.write("hello,this is my first file")
f.flush()
f=open("python.txt","r",encoding="utf-8")
content=f.read()
print(f"the content1 is:{content}")
f=open("python.txt","a")
f.write("I want to be a successful people,just to do!")
f.flush()
f=open("python.txt","r",encoding="utf-8")
last_content=f.read()
print(f"the content2 is:{last_content}")
